### ISSUE TITLE
custom title-slide class not showing author

### ISSUE THREAD

**Issue by shannonpileggi** [spcanelon/RLadies-xaringan-template#2]
Hi Siliva! I modified my `yaml` title, subtitle, author, instititute and date as follows:

```
---
title: "A job interview presentation inspired by the R community"
subtitle: "How #tidytuesday and twitter helped me secure a job offer"
author: "Shannon Pileggi"
institute: "R-Ladies Miami Meet-up"
date: "April 22, 2021"
output:
  xaringan::moon_reader:
    lib_dir: libs
    css:
      - default
      - rladies
      - rladies-fonts
      - css/rladies-mod.css
    seal: false
    nature:
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
      ratio: 4:3
---
```

and the title slide renders as:

![image](https://user-images.githubusercontent.com/17747575/114111244-8992ed00-98a7-11eb-9697-06c98216e6ca.png)

should I remove the `title-class` or make modifications to it so that the `yaml` parameters pass through?
